---
name: Bug report
description: Create a report to help us improve
labels:
  - needs analysis
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is. Anything related to actual message definitions in [ebusd-configuration](https://github.com/john30/ebusd-configuration), serial bridge in [ebusd-esp](https://github.com/john30/ebusd-esp), or [eBUS adapter v3/v2](https://github.com/eBUS/adapter) do not belong here! Use the appropriate repository for those.
      placeholder: e.g. during startup, an error message as described below is reported instead of...
    validations:
      required: true
  - type: textarea
    id: actual_behaviour
    attributes:
      label: Actual behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. when starting ebusd, it gives an error message...
    validations:
      required: true
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. when starting ebusd, it should not give an error message...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: ebusd version
      description: the ebusd version in use
      options:
        - current source from git
        - '22.4'
        - '22.3'
        - '22.2'
        - '22.1'
        - '21.3'
        - '21.2'
        - other
    validations:
      required: true
  - type: input
    id: args
    attributes:
      label: ebusd arguments
      description: the arguments with which ebusd is started (including the ENV vars starting with EBUSD_)
      placeholder: e.g. copy the EBUSD_OPTS line from /etc/default/ebusd
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: the operating system in use
      options:
        - Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)
        - Debian 10 (Buster) / Ubuntu 18-19 / Raspbian 10 / Raspberry Pi OS 10 (including lite)
        - Debian 9 (Stretch) / Ubuntu 16-17 / Raspbian 9 / Raspberry Pi OS 9 (including lite)
        - other
    validations:
      required: true
  - type: dropdown
    id: architecture
    attributes:
      label: CPU architecture
      description: the CPU architecture in use (output of `dpkg --print-architecture` or `uname -m`)
      options:
        - x64
        - i386
        - armv7l
        - arm64
        - other
    validations:
      required: true
  - type: dropdown
    id: docker
    attributes:
      label: Dockerized
      description: indicate if a docker container is used
      options:
        - devel
        - latest
        - same as ebusd version
        - other
  - type: dropdown
    id: interface
    attributes:
      label: Hardware interface
      description: the eBUS hardware interface in use
      options:
        - adapter 3.1 USB
        - adapter 3.1 WiFi
        - adapter 3.1 Ethernet
        - adapter 3.1 RPi
        - adapter 3.0 USB
        - adapter 3.0 WiFi
        - adapter 3.0 Ethernet
        - adapter 3.0 RPi
        - adapter 2
        - Esera USB
        - Esera Ethernet
        - other
    validations:
      required: true
  - type: dropdown
    id: integration
    attributes:
      label: Related integration
      description: the integration to which this issue is related
      multiple: true
      options:
        - TCP (cmdline client like ebusctl or netcat)
        - HTTP
        - MQTT generic
        - MQTT Home Assistant via mqtt-hassio.cfg
        - KNX
        - other
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant ebusd log lines found in /var/log/ebusd.log
      placeholder: e.g. paste the lines from /var/log/ebusd.log
    validations:
      required: true
